### ISSUE TITLE
Add local host docs

### ISSUE THREAD

**Issue by EvanLovely** [drupal-pattern-lab/drupal-pattern-lab.github.io#1]
Would be great to get a gemfile and docs on how to spin up locally.

https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll

**Comment by illepic** [comment]
I'll take.

**Comment by EvanLovely** [comment]
Still need docs in readme

**Comment by sghoweri** [comment]
@EvanLovely @illepic almost done with these setup instructions
