### ISSUE TITLE
Define purpose and scope of projects

### ISSUE THREAD

**Issue by aleksip** [drupal-pattern-lab/drupal-pattern-lab.github.io#10]
Is everything under this GitHub organization going to be tightly focused on Pattern Lab related things only?

I think it might often be hard to make a distinction between the more general 'component based theming in Drupal' best practices etc. and Pattern Lab specific ones. If we want to be Pattern Lab specific, where is the home for the more general stuff?

If we want to go for a more general approach, then maybe we could still change the name of the organization to something more general at this point? "There are only two hard things in Computer Science" so of course I don't have a suggestion for a good name. :)

**Comment by EvanLovely** [comment]
Moved this here: https://github.com/drupal-pattern-lab/roadmap/issues/1
