### ISSUE TITLE
Consolidate Twig best practices

### ISSUE THREAD

**Issue by evanmwillhite** [drupal-pattern-lab/drupal-pattern-lab.github.io#5]
If possible, it would be great to consolidate examples of Twig/PL best practices into a single location(s). I can see possibly either both documentation and a Drupal starter kit (a la [Drupal-Lab](https://github.com/phase2/drupal-lab/tree/master/web/themes/dashing)) or possibly even just one of those?

The only place I could see this getting hairy is if we differ too much on implementation, but if we can agree enough it would be nice to provide a good starting point for people new to this:

1. Pattern Lab installation inside of Drupal
2. Integrating multiple kinds of PL files (atoms, molecules, etc.) into multiple kinds of Drupal files (fields, nodes, views, paragraphs, blocks, bricks, etc.)

**Comment by EvanLovely** [comment]
Moved here: https://github.com/drupal-pattern-lab/roadmap/issues/4
