### ISSUE TITLE
Point community to Drupal Pattern Lab Edition

### ISSUE THREAD

**Issue by evanmwillhite** [drupal-pattern-lab/drupal-pattern-lab.github.io#6]
It makes sense to promote a single Pattern Lab edition as the "blessed" Drupal edition, especially if the difference between it and the Twig edition is enough to justify a separate project.

Currently, it looks like the difference is in the twig-components? If so, could we separate off this just this piece into an add-on to the Twig edition? If not, do we want to add [the Twig namespaces plugin](https://github.com/EvanLovely/plugin-twig-namespaces) into the edition?

**Comment by aleksip** [comment]
The Drupal edition adds `drupal-twig-components`, `plugin-data-transform` and Drupal-specific StarterKit suggestions.

But as not everyone uses `drupal-twig-components` or `plugin-data-transform` and the current StarterKit install method isn't really developer-friendly (in my opinion at least), I'd vote for using the plain Twig edition as the recommended edition and providing good documentation about adding Drupal-related plugins, installing Drupal-related StarterKits etc.

**Comment by EvanLovely** [comment]
Moved here: https://github.com/drupal-pattern-lab/roadmap/issues/2
