### ISSUE TITLE
Placeholder for Gulp/NPM task conversation

### ISSUE THREAD

**Issue by evanmwillhite** [drupal-pattern-lab/drupal-pattern-lab.github.io#7]
There's a lot of cross-over in terms of what projects like Pattern Lab Starter and Emulsify are trying to accomplish at a base-level when it comes to Sass, JS and Pattern Lab. Some of these are specific to company needs, but likely some of them can be put into a project we all use/support.

**Comment by sghoweri** [comment]
Moved to https://github.com/drupal-pattern-lab/roadmap/issues/3
