### ISSUE TITLE
Setup VERY basic theme

### ISSUE THREAD

**Issue by EvanLovely** [drupal-pattern-lab/drupal-pattern-lab.github.io#9]

**Comment by evanmwillhite** [comment]
Maybe use an existing one (http://jekyllthemes.org/themes/jekyll-simple/)? I only looked at the first page of themes, but there might be some there to just get something up quickly.

**Comment by EvanLovely** [comment]
Looks like only these themes are supported on GH Pages: https://pages.github.com/themes/

**Comment by sghoweri** [comment]
@EvanLovely @evanmwillhite I threw something quick together using the https://pages-themes.github.io/cayman/ theme as a base -- should have it up in just a couple minutes for feedback

**Comment by sghoweri** [comment]
Closing this out - boom!
